include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - lib/client.dart
    - lib/server/*.g.dart
    - test/_data/**

linter:
  rules:
    avoid_shadowing_type_parameters: false
    await_only_futures: true